### PR TITLE
Add support for HTTPS

### LINKED ISSUE #3: Add support for HTTPS

### PR DESCRIPTION
**Pull request by stevenroose**
For more info on configuring HTTPS serving in Dart, take a look at this gist:
https://gist.github.com/stevenroose/e6abde14258971eae982

Fixes #3

### CODE REVIEW

**Comment by kevmoo** [comment]
Replaced by https://github.com/dart-lang/shelf/issues/5

**Comment by nex3** [comment]
For future reference, you can push additional changes to an existing pull request.

**Comment by sethladd** [comment]
I've always been curious... if we push additional changes to an existing pull request, how do we do that *and* squash all our commits?

How do I update a PR *and* squash into a single commit, after I've already uploaded my PR?

(this assumes that ideally that each PR is a single squashed commit)

**Comment by kevmoo** [comment]
You have to `push --force` into your pull request.

My thought: the LGTMer should do the squash and push – not merge.

**Comment by sethladd** [comment]
@kevmoo ahh... that's your cool snippet:

```
[alias]
  pr = "!f() { git fetch origin refs/pull/$1/head:pr/$1; } ; f"
```

Do we lose any attribution if a team member (you or I) are the ones doing the actual merge into master?

**Comment by kevmoo** [comment]
Nope.

See this
https://github.com/angular/angular/commit/03793d0714eb406927dbd037161b1c64979a2009

The is a difference between committer and author.

**Comment by nex3** [comment]
There's also usually some minor additional work to be done—cleaning up the style, incrementing the version, and such—that's easier to do ourselves than ask external contributors to do.

I often don't squash the commits, though, and instead use `merge --no-ff`; this still creates a single commit on `master`, but it preserves more history, which is especially nice when some of the change comes from the external contributor and some comes from your own cleanups.

**Pull request closed without merging**
