### PR TITLE
Merge shelf_router / shelf_router_generator

### PR DESCRIPTION
**Pull request by jonasfj**
You can also pull in tags from my fork.

I've updated the READMEs to reflect that these packages are no longer carry the disclaimer:
> Disclaimer: This is not an officially supported Google product.

We can probably change the LICENSE too, since everything is under CLA in the old repository.

### CODE REVIEW

**Comment by jonasfj** [comment]
do not squash merge, then there is no history. Or just merge manually with git pull/push

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
There's a tool in...`tool` that will update the readme as well

**Comment by devoncarew** [comment]
> There's a tool in...`tool` that will update the readme as well

Yup - I want to update that, then re-generate the readme (but I don't want to create merge conflicts for this PR if I can help it).

**Comment by jonasfj** [comment]
@kevmoo, @devoncarew feel free to merge this.

I'm not an admin, so I can't land with a "merge commit". It's also entirely possible that "rebase and merge" is fine.

(sorry, I forgot all about this)

**Comment by kevmoo** [comment]
Let me try to do the commit to keep history

**Pull request merged**
