### PR TITLE
Prepare the release of shelf_router_generator

### PR DESCRIPTION
**Pull request by isoos**

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
One test to fix!

**Comment by isoos** [comment]
Any idea why that test is failing on this PR?
Maybe it only needs a rerun? (I can't trigger it)

**Comment by kevmoo** [comment]
> Any idea why that test is failing on this PR? Maybe it only needs a rerun? (I can't trigger it)

It looks like it's forcing pre-null-safety.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/shelf/pull/317

**Comment by isoos** [comment]
Rebased, tests are passing. Note: I don't have merge permissions, somebody else should do it + also release :)

**Comment by kevmoo** [comment]
published!

**Comment by isoos** [comment]
Thank you!

**Pull request merged**
